#pragma kernel CSMain

#define SQRT2 1.4142
#define FLT_MAX 3.402823466e+38

#define WALKABLE_BIT 1
#define EXPLORED_BIT 2

RWTexture2D<int> _PixelState; // used for determining the border
RWTexture2D<float3> _Flow;

// Regular color data, taken from camera
// x/r: cost
// y/g: height
// z/b: <unused>
// w/a: bit info
Texture2D<float4> _TileData;

const int2 offsets[] = { int2(-1,1), int2(0,1), int2(1,1), int2(1,0), int2(1,-1), int2(0,-1), int2(-1,-1), int2(-1,0) };
const float costs[] = { SQRT2, 1, SQRT2, 1, SQRT2, 1, SQRT2, 1 };

inline bool BitIs0(in uint bits, uint bitNum) { return (bits & bitNum) != 0; }
inline bool BitIs1(in uint bits, uint bitNum) { return (bits & bitNum) == 0; }
inline void SetBit1(out uint bits, uint bitNum) { bits |= bitNum; }
inline void SetBit0(out uint bits, uint bitNum) { bits &= ~bitNum; }

[numthreads(8,8,1)]
void CSMain(uint3 groupID : SV_GroupID, uint3 threadID : SV_GroupThreadID)
{
    int2 pixel = groupID.xy * 8 + threadID.xy;

    // 0 = not on border
    // 1 = in border
    // 2 = claimed by thread
    if (_PixelState[pixel] == 0) return; // Return early if the pixel is not on border, all threads quit early here so *MAYBE* no need to use atomics
    int prevValue;
    InterlockedCompareExchange(_PixelState[pixel], 1, 2, prevValue);
    if(prevValue == 2) return; // Quit out early if there is already a thread that claimed that pixel
 
    float min = FLT_MAX;
    float3 flow;
    for (int i = 0; i < 8; i++)
    {
        float4 tData = _TileData[pixel + offsets[i]];
        
        uint tBits = asuint(tData.w);

        if (BitIs0(tBits, WALKABLE_BIT)) 
            continue;
        
        // Adjacent unexplored pixels should be marked as the next border
        if (BitIs0(tBits, EXPLORED_BIT))
        {
            _PixelState[pixel + offsets[i]] = 1;
            continue;
        }
        
        // Adjacent explored pixels are used to determine the flow direction
        float cur = costs[i] + tData.r;
        if (cur < min)
        {
            min = cur;
            flow = float3(offsets[i].x, tData.g, offsets[i].y);
        }
    }

    _Flow[pixel] = flow;
    _PixelState[pixel] = 0; // Mark this pixel as no longer claimed by thread
}